CREATE SCHEMA IF NOT EXISTS `Products` DEFAULT CHARACTER SET utf8 ;
USE `Products` ;

CREATE TABLE IF NOT EXISTS `Products`.`USERS` (
 `userId` INT NOT NULL AUTO_INCREMENT,
 `userEmail` VARCHAR(255) NOT NULL,
 `userPassword` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`userId`));
